// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package person;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:classes.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Field 1: Unique ID for a person
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <pre>
   * Field 2: Full name of the person
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * Field 2: Full name of the person
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Field 3: Email is optional — user may or may not provide it.
   * </pre>
   *
   * <code>string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <pre>
   * Field 3: Email is optional — user may or may not provide it.
   * </pre>
   *
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   * Field 4: The person's job information.
   * This uses a message from Job.proto (composition).
   * </pre>
   *
   * <code>.classes.Job job = 4;</code>
   */
  boolean hasJob();
  /**
   * <pre>
   * Field 4: The person's job information.
   * This uses a message from Job.proto (composition).
   * </pre>
   *
   * <code>.classes.Job job = 4;</code>
   */
  job.Job getJob();
  /**
   * <pre>
   * Field 4: The person's job information.
   * This uses a message from Job.proto (composition).
   * </pre>
   *
   * <code>.classes.Job job = 4;</code>
   */
  job.JobOrBuilder getJobOrBuilder();

  /**
   * <pre>
   * Field 5: A person can have multiple phone numbers.
   * `repeated` turns this into a list.
   * </pre>
   *
   * <code>repeated string phone_numbers = 5;</code>
   */
  java.util.List<java.lang.String>
      getPhoneNumbersList();
  /**
   * <pre>
   * Field 5: A person can have multiple phone numbers.
   * `repeated` turns this into a list.
   * </pre>
   *
   * <code>repeated string phone_numbers = 5;</code>
   */
  int getPhoneNumbersCount();
  /**
   * <pre>
   * Field 5: A person can have multiple phone numbers.
   * `repeated` turns this into a list.
   * </pre>
   *
   * <code>repeated string phone_numbers = 5;</code>
   */
  java.lang.String getPhoneNumbers(int index);
  /**
   * <pre>
   * Field 5: A person can have multiple phone numbers.
   * `repeated` turns this into a list.
   * </pre>
   *
   * <code>repeated string phone_numbers = 5;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumbersBytes(int index);
}
