// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package job;

/**
 * <pre>
 * Enum for job categories
 * </pre>
 *
 * Protobuf enum {@code classes.JobType}
 */
public enum JobType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Default zero value is mandatory in proto3.
   * </pre>
   *
   * <code>JOB_TYPE_UNSPECIFIED = 0;</code>
   */
  JOB_TYPE_UNSPECIFIED(0),
  /**
   * <code>FULL_TIME = 1;</code>
   */
  FULL_TIME(1),
  /**
   * <code>PART_TIME = 2;</code>
   */
  PART_TIME(2),
  /**
   * <code>INTERN = 3;</code>
   */
  INTERN(3),
  /**
   * <code>FREELANCE = 4;</code>
   */
  FREELANCE(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Default zero value is mandatory in proto3.
   * </pre>
   *
   * <code>JOB_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int JOB_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>FULL_TIME = 1;</code>
   */
  public static final int FULL_TIME_VALUE = 1;
  /**
   * <code>PART_TIME = 2;</code>
   */
  public static final int PART_TIME_VALUE = 2;
  /**
   * <code>INTERN = 3;</code>
   */
  public static final int INTERN_VALUE = 3;
  /**
   * <code>FREELANCE = 4;</code>
   */
  public static final int FREELANCE_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static JobType valueOf(int value) {
    return forNumber(value);
  }

  public static JobType forNumber(int value) {
    switch (value) {
      case 0: return JOB_TYPE_UNSPECIFIED;
      case 1: return FULL_TIME;
      case 2: return PART_TIME;
      case 3: return INTERN;
      case 4: return FREELANCE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<JobType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      JobType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<JobType>() {
          public JobType findValueByNumber(int number) {
            return JobType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return job.JobOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final JobType[] VALUES = values();

  public static JobType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private JobType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:classes.JobType)
}

