// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package job;

public interface JobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:classes.Job)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Field 1: Job title (e.g., Software Engineer)
   * </pre>
   *
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * Field 1: Job title (e.g., Software Engineer)
   * </pre>
   *
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * Field 2: Company the person works at
   * </pre>
   *
   * <code>string company = 2;</code>
   */
  java.lang.String getCompany();
  /**
   * <pre>
   * Field 2: Company the person works at
   * </pre>
   *
   * <code>string company = 2;</code>
   */
  com.google.protobuf.ByteString
      getCompanyBytes();

  /**
   * <pre>
   * Field 3: Person’s annual salary in USD
   * </pre>
   *
   * <code>uint32 salary = 3;</code>
   */
  int getSalary();

  /**
   * <pre>
   * Field 4: Job type represented as an enumeration.
   * </pre>
   *
   * <code>.classes.JobType type = 4;</code>
   */
  int getTypeValue();
  /**
   * <pre>
   * Field 4: Job type represented as an enumeration.
   * </pre>
   *
   * <code>.classes.JobType type = 4;</code>
   */
  job.JobType getType();
}
