// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package job;

public final class JobOuterClass {
  private JobOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_classes_Job_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_classes_Job_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tJob.proto\022\007classes\"U\n\003Job\022\r\n\005title\030\001 \001" +
      "(\t\022\017\n\007company\030\002 \001(\t\022\016\n\006salary\030\003 \001(\r\022\036\n\004t" +
      "ype\030\004 \001(\0162\020.classes.JobType*\\\n\007JobType\022\030" +
      "\n\024JOB_TYPE_UNSPECIFIED\020\000\022\r\n\tFULL_TIME\020\001\022" +
      "\r\n\tPART_TIME\020\002\022\n\n\006INTERN\020\003\022\r\n\tFREELANCE\020" +
      "\004B\007\n\003jobP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_classes_Job_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_classes_Job_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_classes_Job_descriptor,
        new java.lang.String[] { "Title", "Company", "Salary", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
