// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package person;

/**
 * <pre>
 * Person message definition
 * </pre>
 *
 * Protobuf type {@code classes.Person}
 */
public  final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:classes.Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    id_ = 0;
    name_ = "";
    email_ = "";
    phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Person(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 34: {
            job.Job.Builder subBuilder = null;
            if (job_ != null) {
              subBuilder = job_.toBuilder();
            }
            job_ = input.readMessage(job.Job.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(job_);
              job_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              phoneNumbers_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            phoneNumbers_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        phoneNumbers_ = phoneNumbers_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return person.PersonOuterClass.internal_static_classes_Person_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return person.PersonOuterClass.internal_static_classes_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            person.Person.class, person.Person.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <pre>
   * Field 1: Unique ID for a person
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * Field 2: Full name of the person
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Field 2: Full name of the person
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  private volatile java.lang.Object email_;
  /**
   * <pre>
   * Field 3: Email is optional — user may or may not provide it.
   * </pre>
   *
   * <code>string email = 3;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Field 3: Email is optional — user may or may not provide it.
   * </pre>
   *
   * <code>string email = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOB_FIELD_NUMBER = 4;
  private job.Job job_;
  /**
   * <pre>
   * Field 4: The person's job information.
   * This uses a message from Job.proto (composition).
   * </pre>
   *
   * <code>.classes.Job job = 4;</code>
   */
  public boolean hasJob() {
    return job_ != null;
  }
  /**
   * <pre>
   * Field 4: The person's job information.
   * This uses a message from Job.proto (composition).
   * </pre>
   *
   * <code>.classes.Job job = 4;</code>
   */
  public job.Job getJob() {
    return job_ == null ? job.Job.getDefaultInstance() : job_;
  }
  /**
   * <pre>
   * Field 4: The person's job information.
   * This uses a message from Job.proto (composition).
   * </pre>
   *
   * <code>.classes.Job job = 4;</code>
   */
  public job.JobOrBuilder getJobOrBuilder() {
    return getJob();
  }

  public static final int PHONE_NUMBERS_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList phoneNumbers_;
  /**
   * <pre>
   * Field 5: A person can have multiple phone numbers.
   * `repeated` turns this into a list.
   * </pre>
   *
   * <code>repeated string phone_numbers = 5;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getPhoneNumbersList() {
    return phoneNumbers_;
  }
  /**
   * <pre>
   * Field 5: A person can have multiple phone numbers.
   * `repeated` turns this into a list.
   * </pre>
   *
   * <code>repeated string phone_numbers = 5;</code>
   */
  public int getPhoneNumbersCount() {
    return phoneNumbers_.size();
  }
  /**
   * <pre>
   * Field 5: A person can have multiple phone numbers.
   * `repeated` turns this into a list.
   * </pre>
   *
   * <code>repeated string phone_numbers = 5;</code>
   */
  public java.lang.String getPhoneNumbers(int index) {
    return phoneNumbers_.get(index);
  }
  /**
   * <pre>
   * Field 5: A person can have multiple phone numbers.
   * `repeated` turns this into a list.
   * </pre>
   *
   * <code>repeated string phone_numbers = 5;</code>
   */
  public com.google.protobuf.ByteString
      getPhoneNumbersBytes(int index) {
    return phoneNumbers_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
    }
    if (job_ != null) {
      output.writeMessage(4, getJob());
    }
    for (int i = 0; i < phoneNumbers_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, phoneNumbers_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
    }
    if (job_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getJob());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < phoneNumbers_.size(); i++) {
        dataSize += computeStringSizeNoTag(phoneNumbers_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPhoneNumbersList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof person.Person)) {
      return super.equals(obj);
    }
    person.Person other = (person.Person) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && getEmail()
        .equals(other.getEmail());
    result = result && (hasJob() == other.hasJob());
    if (hasJob()) {
      result = result && getJob()
          .equals(other.getJob());
    }
    result = result && getPhoneNumbersList()
        .equals(other.getPhoneNumbersList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    if (hasJob()) {
      hash = (37 * hash) + JOB_FIELD_NUMBER;
      hash = (53 * hash) + getJob().hashCode();
    }
    if (getPhoneNumbersCount() > 0) {
      hash = (37 * hash) + PHONE_NUMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumbersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static person.Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static person.Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static person.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static person.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static person.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static person.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static person.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static person.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static person.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static person.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static person.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static person.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(person.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Person message definition
   * </pre>
   *
   * Protobuf type {@code classes.Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:classes.Person)
      person.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return person.PersonOuterClass.internal_static_classes_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return person.PersonOuterClass.internal_static_classes_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              person.Person.class, person.Person.Builder.class);
    }

    // Construct using person.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      name_ = "";

      email_ = "";

      if (jobBuilder_ == null) {
        job_ = null;
      } else {
        job_ = null;
        jobBuilder_ = null;
      }
      phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return person.PersonOuterClass.internal_static_classes_Person_descriptor;
    }

    @java.lang.Override
    public person.Person getDefaultInstanceForType() {
      return person.Person.getDefaultInstance();
    }

    @java.lang.Override
    public person.Person build() {
      person.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public person.Person buildPartial() {
      person.Person result = new person.Person(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.name_ = name_;
      result.email_ = email_;
      if (jobBuilder_ == null) {
        result.job_ = job_;
      } else {
        result.job_ = jobBuilder_.build();
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        phoneNumbers_ = phoneNumbers_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.phoneNumbers_ = phoneNumbers_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof person.Person) {
        return mergeFrom((person.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(person.Person other) {
      if (other == person.Person.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (other.hasJob()) {
        mergeJob(other.getJob());
      }
      if (!other.phoneNumbers_.isEmpty()) {
        if (phoneNumbers_.isEmpty()) {
          phoneNumbers_ = other.phoneNumbers_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.addAll(other.phoneNumbers_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      person.Person parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (person.Person) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <pre>
     * Field 1: Unique ID for a person
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <pre>
     * Field 1: Unique ID for a person
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Field 1: Unique ID for a person
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Field 2: Full name of the person
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Field 2: Full name of the person
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Field 2: Full name of the person
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Field 2: Full name of the person
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Field 2: Full name of the person
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <pre>
     * Field 3: Email is optional — user may or may not provide it.
     * </pre>
     *
     * <code>string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Field 3: Email is optional — user may or may not provide it.
     * </pre>
     *
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Field 3: Email is optional — user may or may not provide it.
     * </pre>
     *
     * <code>string email = 3;</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Field 3: Email is optional — user may or may not provide it.
     * </pre>
     *
     * <code>string email = 3;</code>
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Field 3: Email is optional — user may or may not provide it.
     * </pre>
     *
     * <code>string email = 3;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private job.Job job_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        job.Job, job.Job.Builder, job.JobOrBuilder> jobBuilder_;
    /**
     * <pre>
     * Field 4: The person's job information.
     * This uses a message from Job.proto (composition).
     * </pre>
     *
     * <code>.classes.Job job = 4;</code>
     */
    public boolean hasJob() {
      return jobBuilder_ != null || job_ != null;
    }
    /**
     * <pre>
     * Field 4: The person's job information.
     * This uses a message from Job.proto (composition).
     * </pre>
     *
     * <code>.classes.Job job = 4;</code>
     */
    public job.Job getJob() {
      if (jobBuilder_ == null) {
        return job_ == null ? job.Job.getDefaultInstance() : job_;
      } else {
        return jobBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Field 4: The person's job information.
     * This uses a message from Job.proto (composition).
     * </pre>
     *
     * <code>.classes.Job job = 4;</code>
     */
    public Builder setJob(job.Job value) {
      if (jobBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        job_ = value;
        onChanged();
      } else {
        jobBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Field 4: The person's job information.
     * This uses a message from Job.proto (composition).
     * </pre>
     *
     * <code>.classes.Job job = 4;</code>
     */
    public Builder setJob(
        job.Job.Builder builderForValue) {
      if (jobBuilder_ == null) {
        job_ = builderForValue.build();
        onChanged();
      } else {
        jobBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Field 4: The person's job information.
     * This uses a message from Job.proto (composition).
     * </pre>
     *
     * <code>.classes.Job job = 4;</code>
     */
    public Builder mergeJob(job.Job value) {
      if (jobBuilder_ == null) {
        if (job_ != null) {
          job_ =
            job.Job.newBuilder(job_).mergeFrom(value).buildPartial();
        } else {
          job_ = value;
        }
        onChanged();
      } else {
        jobBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Field 4: The person's job information.
     * This uses a message from Job.proto (composition).
     * </pre>
     *
     * <code>.classes.Job job = 4;</code>
     */
    public Builder clearJob() {
      if (jobBuilder_ == null) {
        job_ = null;
        onChanged();
      } else {
        job_ = null;
        jobBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Field 4: The person's job information.
     * This uses a message from Job.proto (composition).
     * </pre>
     *
     * <code>.classes.Job job = 4;</code>
     */
    public job.Job.Builder getJobBuilder() {
      
      onChanged();
      return getJobFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Field 4: The person's job information.
     * This uses a message from Job.proto (composition).
     * </pre>
     *
     * <code>.classes.Job job = 4;</code>
     */
    public job.JobOrBuilder getJobOrBuilder() {
      if (jobBuilder_ != null) {
        return jobBuilder_.getMessageOrBuilder();
      } else {
        return job_ == null ?
            job.Job.getDefaultInstance() : job_;
      }
    }
    /**
     * <pre>
     * Field 4: The person's job information.
     * This uses a message from Job.proto (composition).
     * </pre>
     *
     * <code>.classes.Job job = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        job.Job, job.Job.Builder, job.JobOrBuilder> 
        getJobFieldBuilder() {
      if (jobBuilder_ == null) {
        jobBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            job.Job, job.Job.Builder, job.JobOrBuilder>(
                getJob(),
                getParentForChildren(),
                isClean());
        job_ = null;
      }
      return jobBuilder_;
    }

    private com.google.protobuf.LazyStringList phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensurePhoneNumbersIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        phoneNumbers_ = new com.google.protobuf.LazyStringArrayList(phoneNumbers_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <pre>
     * Field 5: A person can have multiple phone numbers.
     * `repeated` turns this into a list.
     * </pre>
     *
     * <code>repeated string phone_numbers = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPhoneNumbersList() {
      return phoneNumbers_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Field 5: A person can have multiple phone numbers.
     * `repeated` turns this into a list.
     * </pre>
     *
     * <code>repeated string phone_numbers = 5;</code>
     */
    public int getPhoneNumbersCount() {
      return phoneNumbers_.size();
    }
    /**
     * <pre>
     * Field 5: A person can have multiple phone numbers.
     * `repeated` turns this into a list.
     * </pre>
     *
     * <code>repeated string phone_numbers = 5;</code>
     */
    public java.lang.String getPhoneNumbers(int index) {
      return phoneNumbers_.get(index);
    }
    /**
     * <pre>
     * Field 5: A person can have multiple phone numbers.
     * `repeated` turns this into a list.
     * </pre>
     *
     * <code>repeated string phone_numbers = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumbersBytes(int index) {
      return phoneNumbers_.getByteString(index);
    }
    /**
     * <pre>
     * Field 5: A person can have multiple phone numbers.
     * `repeated` turns this into a list.
     * </pre>
     *
     * <code>repeated string phone_numbers = 5;</code>
     */
    public Builder setPhoneNumbers(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneNumbersIsMutable();
      phoneNumbers_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Field 5: A person can have multiple phone numbers.
     * `repeated` turns this into a list.
     * </pre>
     *
     * <code>repeated string phone_numbers = 5;</code>
     */
    public Builder addPhoneNumbers(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneNumbersIsMutable();
      phoneNumbers_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Field 5: A person can have multiple phone numbers.
     * `repeated` turns this into a list.
     * </pre>
     *
     * <code>repeated string phone_numbers = 5;</code>
     */
    public Builder addAllPhoneNumbers(
        java.lang.Iterable<java.lang.String> values) {
      ensurePhoneNumbersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, phoneNumbers_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Field 5: A person can have multiple phone numbers.
     * `repeated` turns this into a list.
     * </pre>
     *
     * <code>repeated string phone_numbers = 5;</code>
     */
    public Builder clearPhoneNumbers() {
      phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Field 5: A person can have multiple phone numbers.
     * `repeated` turns this into a list.
     * </pre>
     *
     * <code>repeated string phone_numbers = 5;</code>
     */
    public Builder addPhoneNumbersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensurePhoneNumbersIsMutable();
      phoneNumbers_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:classes.Person)
  }

  // @@protoc_insertion_point(class_scope:classes.Person)
  private static final person.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new person.Person();
  }

  public static person.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @java.lang.Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Person(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public person.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

