// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package person;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_classes_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_classes_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Person.proto\022\007classes\032\tJob.proto\"c\n\006Pe" +
      "rson\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030" +
      "\003 \001(\t\022\031\n\003job\030\004 \001(\0132\014.classes.Job\022\025\n\rphon" +
      "e_numbers\030\005 \003(\tB\n\n\006personP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          job.JobOuterClass.getDescriptor(),
        }, assigner);
    internal_static_classes_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_classes_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_classes_Person_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Job", "PhoneNumbers", });
    job.JobOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
